# Railway Nixpacks configuration for Chrome/Puppeteer support
[phases.setup]
nixPkgs = [
  "chromium",
  "liberation_ttf",
  "nss",
  "atk",
  "cairo",
  "pango",
  "gdk-pixbuf",
  "gtk3",
  "libdrm",
  "mesa"
]

[phases.install]
cmds = [
  "npm ci --only=production"
]

[phases.build]
cmds = [
  "ln -sf /nix/store/*-chromium-*/bin/chromium /usr/bin/chromium-browser || true",
  "echo 'Chrome dependencies installed successfully'"
]

[start]
cmd = "npm start"

[variables]
PUPPETEER_SKIP_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium-browser"
