[phases.setup]
nixPkgs = ['nodejs_20', 'chromium']

[phases.install]
cmds = ['npm install --production --no-package-lock']

[phases.build]

[start]
cmd = 'npm start'

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'
PUPPETEER_EXECUTABLE_PATH = '/nix/store/*-chromium-*/bin/chromium'
NODE_ENV = 'production'
