[phases.setup]
nixPkgs = [
  'nodejs_20',
  'chromium',
  'liberation_ttf',
  'nss',
  'freetype',
  'harfbuzz'
]

[phases.install]
cmds = ['npm ci --omit=dev']

[phases.build]
cmds = []

[start]
cmd = 'npm start'

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'
PUPPETEER_EXECUTABLE_PATH = '/nix/store/*-chromium-*/bin/chromium'
NODE_ENV = 'production'
